define(["IotApp"],function(IotApp){
	IotApp.config(function($routeProvider){
		$routeProvider.when("/home",{
			templateUrl:"home.html"
		}).when("/error",{
			templateUrl:"error.html"
		}).when("/noright",{
			templateUrl:"noright.html"
		}).when("/sys/config",{
			templateUrl:"system/config.html",
			controller:"SysController"
		}).when("/sys/logs",{
			templateUrl:"logs/sys_logs.html",
			controller:"LogsController"
		}).when("/sys/login/logs",{
			templateUrl:"logs/sys__login_logs.html",
			controller:"LogsController"
		}).when("/sys/menus",{
			templateUrl:"system/sys_menu.html",
			controller:"SysMenuController"
		}).when("/sys/roles",{
			templateUrl:"system/sys_role.html",
			controller:"SysRoleController"
		}).otherwise({
			templateUrl:"home.html"
		});
	});
	
	IotApp.config(function($routeProvider){
		$routeProvider
		 .when("/users/editpwd",{
			templateUrl:"users/editpwd.html",
			controller:"UserController"
		}).when("/users",{
			templateUrl:"users/user_list.html",
			controller:"UserController"
		}).when("/users/add",{
			templateUrl:"users/user_add.html",
			controller:"UserController"
		}).when("/users/:userId",{
			templateUrl:"users/user_detail.html",
			controller:"UserController"
		});
	});
	
	IotApp.config(function($routeProvider){
		$routeProvider
			.when("/pedometer",{
				templateUrl:"equipment/pedometer_list.html",
				controller:"EquipmentController"
			}).when("/pedometer/reader",{
				templateUrl:"equipment/pedometer_reader_list.html",
				controller:"EquipmentController"
			}).when("/pedometer/data",{
				templateUrl:"equipment/pedometer_data_list.html",
				controller:"EquipmentController"				
			}).when("/pedometer/add",{
				templateUrl:"equipment/pedometer_add.html",
				controller:"EquipmentController"
			}).when("/pedometer/reader/add",{
				templateUrl:"equipment/pedometer_reader_add.html",
				controller:"EquipmentController"
			}).when("/pedometer/:serialNo",{
				templateUrl:"equipment/pedometer_detail.html",
				controller:"EquipmentController"
			}).when("/pedometer/reader/:serialNo",{
				templateUrl:"equipment/pedometer_reader_detail.html",
				controller:"EquipmentController"
			});
	});

	IotApp.config(function($routeProvider){
		$routeProvider
			.when("/cabinet",{
				templateUrl:"cabinet/cabinet_list.html",
				controller:"CabinetController"
			}).when("/cabinet/add",{
				templateUrl:"cabinet/cabinet_add.html",
				controller:"CabinetController"
			}).when("/cabinet/door",{
				templateUrl:"cabinet/door_list.html",
				controller:"CabinetController"
			}).when("/cabinet/logs",{
				templateUrl:"cabinet/cabinet_logs.html",
				controller:"CabinetController"
			}).when("/cabinet/:seriesNo",{
				templateUrl:"cabinet/cabinet_detail.html",
				controller:"CabinetController"
			}).when("/cabinet/door/:doorId",{
				templateUrl:"cabinet/door_detail.html",
				controller:"CabinetController"
			});
	});
});